input_folder: "/input"
template_path: "/template.jpg"
samples_folder: "/samples"
output_folder: "/out"
params:
  image_size: 256
  threshold: 0.6
  return_all: False
  offset: 2
  simularity_strategy: "pixel_mse"
  simularity_threshold: 0.001
emo_params: 
  crop_strategy: "MTCNN"
  image_size: 48
